import fs from 'node:fs';
import path from 'node:path';

import { BrokerError } from '../errors.ts';

/**
 * The artifact store: **one directory per lease, and nothing outside it.**
 *
 * `SCHEMA.md` §1.7a. Browser automation produces a lot of files — a console
 * log per tab, a network log, an accessibility snapshot on every navigation
 * and after every action, downloads a page triggers, and screenshots. Left to
 * itself that lands wherever each tool happens to write. Everything the
 * service emits has a defined home here, so nothing has to be hunted for and
 * **a finished lease can be deleted as one directory.**
 *
 * ```
 * <artifact root>/
 *   claims/
 *     <claim id>/
 *       images/       captures, and the crops a comparison produces
 *       snapshots/    accessibility snapshots
 *       console/      console logs
 *       network/      network logs
 *       downloads/    anything a page downloaded
 * ```
 *
 * **One tree, no exceptions to it.** Everything the service writes is under a
 * lease, because a lease is the unit you delete. There is no second area
 * holding images that outlive a lease, because there is no category of image
 * that does — every picture is a capture belonging to whoever took it.
 *
 * ── The two rules this module exists to hold ────────────────────────────
 *
 * **1. Every stored path is relative to the root, never absolute** (§1.7a).
 * The root can move, and an absolute path pins every row to one machine's
 * layout the moment it is written. A relative path plus a root that is
 * configuration survives the move; an absolute path turns it into a data
 * migration. {@link StoredArtifact} therefore carries **both** — the relative
 * path, which is what a caller records, and the absolute one, which is what
 * this process just wrote to and nothing outside this process should keep.
 * They are separate fields rather than one, so a caller cannot store the
 * wrong one by not noticing which it was handed.
 *
 * **2. Nothing lands outside the tree.** Every path this module produces is
 * assembled from a sanitised identifier and a sanitised name, and
 * {@link ArtifactStore.write} asserts the assembled result is under the root
 * before it writes. That second check is belt and braces over
 * `names.ts`'s character rules, and it is worth its cost: the character rules
 * are the thing a future change is most likely to loosen, and this assertion
 * fails loudly rather than writing somewhere surprising.
 *
 * ── What this does NOT do ───────────────────────────────────────────────
 *
 * **Nothing sweeps a file.** There is no retention, and the absence is a
 * ruling rather than a gap (`MILESTONES.md` #45, `SCHEMA.md` §6.2): a
 * retention window would introduce a failure the caller cannot diagnose — an
 * identifier valid last week and silently invalid now, for a reason nothing in
 * the response mentions. Deleting a lease's directory is a thing somebody can
 * do; it is not a thing this service schedules.
 *
 * **Nothing here reads a path from a caller.** `artifact.no_request_path`
 * (§7.3) is about the path that serves bytes, and this module is the other
 * half of why that rule is satisfiable: a recorded relative path resolves
 * under the root through {@link ArtifactStore.resolve}, which refuses anything
 * that escapes, so traversal has no input to arrive through.
 */

/** The subfolders §1.7a defines, by what goes in them. */
export type ArtifactKind = 'images' | 'snapshots' | 'console' | 'network' | 'downloads';

/**
 * Every kind, in the order §1.7a lists them.
 *
 * **Named entries, not a derived list.** A test that walks this array and
 * asserts each directory exists is a test that goes green when an entry is
 * deleted, because it would then be walking a shorter list. So the test that
 * matters names each folder outright and this constant is for code that
 * genuinely needs to iterate.
 */
export const ARTIFACT_KINDS: readonly ArtifactKind[] = [
  'images',
  'snapshots',
  'console',
  'network',
  'downloads',
];

/**
 * Where a written file is, said twice on purpose.
 *
 * See rule one in this file's header: the relative path is what a row records,
 * the absolute path is what this process just wrote to. Two fields rather than
 * one because a single field would be recorded by whoever happened to receive
 * it, and the wrong choice is invisible until the root moves.
 */
export interface StoredArtifact {
  /** **What goes in the database** — relative to the root, always (§1.7a). */
  readonly relativePath: string;
  /** Where it is on this machine, right now. Never stored anywhere. */
  readonly absolutePath: string;
  readonly bytes: number;
}

/**
 * A path segment that identifies a lease, made safe.
 *
 * A claim identifier is generated by this service and is already safe, so this
 * looks redundant — and it is not, for the reason rule two above gives: the
 * value arriving here is the one thing in the assembled path that came from
 * outside this module, and a check that only holds while an upstream promise
 * holds is a check that fails silently the day the promise changes.
 */
function safeSegment(value: string, what: string): string {
  const reduced = value.toLowerCase().replace(/[^a-z0-9-]/g, '');
  if (reduced === '' || reduced !== value.toLowerCase()) {
    throw new BrokerError(
      'artifact.no_request_path',
      `${what} is not usable as a directory name. Expected letters, digits and hyphens; found ${JSON.stringify(value)}.`,
    );
  }
  return reduced;
}

/**
 * Is this path absolute in **either** namespace?
 *
 * ── Why the platform's own answer is the wrong one ──────────────────────
 *
 * `path.isAbsolute` asks the namespace the host process happens to be running
 * in, and the two namespaces disagree about what an absolute path even is. On
 * a platform whose separator is the forward slash, `C:` followed by a
 * backslash is not a root — it is a perfectly legal **relative filename that
 * contains backslashes**, so the refusal never fires and the path is joined
 * onto the root as one long oddly-named file. The same string refuses on the
 * other platform. Identical input, opposite outcome, from the same code.
 *
 * That is not a hypothetical, and this codebase already answers it in one
 * place: `store/network-path.ts` reads its share root with
 * {@link path.win32.parse} **unconditionally**, on every platform, for
 * exactly this reason. This follows that approach rather than inventing a
 * second one, so both guards recognise both spellings the same way.
 *
 * ── Both checks, and honesty about what the second one adds ─────────────
 *
 * **The two are not independently load-bearing, and pretending otherwise
 * would mislead the next reader.** The drive-letter parser also reports a
 * root for a leading forward slash, so deleting the first check changes no
 * outcome any test observes — deleting the *second* is what turns the guard
 * off for a drive-qualified name and a share.
 *
 * The first check stays because this rule is "absolute in either namespace"
 * and one line per namespace is how that reads as code. Leaning on one
 * parser's incidental coverage of the other's case would make the rule
 * correct by coincidence rather than by statement.
 *
 * A guard that only fires on the platform it was written on is worse than no
 * guard, because it reports a protection that does not exist.
 */
function isAbsoluteInEitherNamespace(target: string): boolean {
  // POSIX: a leading forward slash. Named for its own sake — see above.
  if (path.posix.isAbsolute(target)) {
    return true;
  }
  // The other namespace: a drive letter followed by a colon and a separator,
  // in either separator spelling; a two-separator share prefix naming a host
  // and a share; and a bare leading backslash. Reading the parsed root covers
  // every one of those spellings without this file having to enumerate them
  // as patterns of its own.
  return path.win32.parse(target).root !== '';
}

export class ArtifactStore {
  readonly #root: string;

  /**
   * @param root `BROKER_ARTIFACTS_ROOT`, already resolved by the environment
   *   snapshot. Taken as a string rather than read from the environment here,
   *   so that this class has no configuration of its own and a test does not
   *   have to arrange a process environment to use one.
   */
  constructor(root: string) {
    this.#root = path.resolve(root);
  }

  /** Where the tree is rooted. Read by nothing that stores it. */
  get root(): string {
    return this.#root;
  }

  /**
   * The directory for one lease's artefacts of one kind, created if absent.
   *
   * Created lazily rather than at claim time: a lease that takes no captures
   * should not leave an empty tree behind, and there is no moment in a
   * daemonless service at which a setup step could have run instead.
   */
  directoryFor(claimId: string, kind: ArtifactKind): string {
    const directory = path.join(
      this.#root,
      'claims',
      safeSegment(claimId, 'A claim identifier'),
      kind,
    );
    fs.mkdirSync(directory, { recursive: true });
    return directory;
  }

  /**
   * Write one file into a lease's tree, and report where it went **relative to
   * the root**.
   *
   * The refusal below is the second of this file's two rules, and it asks two
   * questions rather than one. It compares the resolved destination against
   * the resolved root, which catches a name that climbs out through `..`; and
   * it asks {@link isAbsoluteInEitherNamespace} whether the supplied name was
   * absolute in **either** namespace, which is what catches the spellings the
   * host platform does not read as roots. Both are needed — see that
   * function for why one platform's answer is not the answer.
   */
  write(
    claimId: string,
    kind: ArtifactKind,
    fileName: string,
    contents: Uint8Array,
  ): StoredArtifact {
    const directory = this.directoryFor(claimId, kind);
    const absolutePath = path.resolve(directory, fileName);
    const relative = path.relative(this.#root, absolutePath);
    // `..` at the front means the destination climbed out of the root; an
    // absolute answer means it was never under it at all. Either is a bug in
    // whatever composed the name, and neither may be written.
    //
    // **The supplied name is tested as well as the computed result**, and that
    // is not belt and braces — it is the only check that catches a name
    // absolute in the *other* namespace. Such a name is a legal relative
    // filename to `path.resolve` here, so it resolves quietly under the root
    // and the computed answer is relative and clean. Nothing downstream can
    // notice; the name itself has to be asked.
    if (
      relative.startsWith('..') ||
      isAbsoluteInEitherNamespace(relative) ||
      isAbsoluteInEitherNamespace(fileName)
    ) {
      throw new BrokerError(
        'artifact.no_request_path',
        `A capture would have been written outside the artifact root. Refusing: ${JSON.stringify(fileName)} does not resolve under it.`,
      );
    }
    fs.writeFileSync(absolutePath, contents);
    return {
      // Stored with forward slashes whatever platform wrote it, so a row
      // written on one machine reads on another. A separator is presentation;
      // making it part of the stored value would reintroduce, one layer down,
      // exactly the machine-specificity rule one exists to remove.
      relativePath: relative.split(path.sep).join('/'),
      absolutePath,
      bytes: contents.byteLength,
    };
  }

  /**
   * Turn a recorded relative path back into a location on this machine.
   *
   * **This is the only way bytes are ever served** (§1.9, `artifact.no_request_path`):
   * a recorded path resolves under the root or nothing is served, so a caller
   * never supplies a filesystem path and traversal has no input to arrive
   * through. The refusal is the same one `write` makes, from the other
   * direction, and it is deliberately duplicated rather than shared through a
   * flag — the two callers are asking different questions and a shared
   * parameterised helper would be one edit away from answering only one of
   * them.
   */
  resolve(relativePath: string): string {
    const absolutePath = path.resolve(this.#root, relativePath);
    const relative = path.relative(this.#root, absolutePath);
    if (
      relative.startsWith('..') ||
      isAbsoluteInEitherNamespace(relative) ||
      isAbsoluteInEitherNamespace(relativePath)
    ) {
      throw new BrokerError(
        'artifact.no_request_path',
        `A recorded path does not resolve under the artifact root. Refusing to serve ${JSON.stringify(relativePath)}.`,
      );
    }
    return absolutePath;
  }
}
